docker-compose-yaml: docker-compose.yml

project: drupalcontribution-org

tasks:
  pre-rollout:
    - run:
        name: drush sql-dump
        command: mkdir -p /app/private/ && drush sql-dump --structure-tables-key=common --ordered-dump --gzip --result-file=/app/private/pre-deploy-dump.sql.gz
        service: cli

  post-rollout:
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  9.x:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
