_core:
  default_config_hash: QaBP0FEBQFVu_6eshMIR_MgA6mVmi5AeVqtHIYSzXNw
shariff_services:
  twitter: twitter
  facebook: facebook
  addthis: addthis
shariff_theme: colored
shariff_css: complete
shariff_orientation: horizontal
