_core:
  default_config_hash: AdUpdSJIPyS_pKdFBRPgAt0tqqF0L2fmO-83Kw5JlnA
limit_search_and_mention: false
fields:
  field_profile_phone_number: 1
  field_profile_address: 1
  field_profile_expertise: 0
  field_profile_first_name: 0
  field_profile_function: 0
  field_profile_image: 0
  field_profile_interests: 0
  field_profile_last_name: 0
  field_profile_organization: 0
  field_profile_organization_tag: 0
  field_profile_self_introduction: 0
disclaimer:
  value: "<p><strong>Please note:</strong></p>\r\n\r\n<p>Other people will still be able to find you when they search for a value of some of these fields (e.g. Amsterdam for City value). The information you choose to hide will still be visible to the managers of this site. It is also possible that some of the options below are disabled by the managers of this site.</p>\r\n"
  format: basic_html
