_core:
  default_config_hash: wYc5ef7Dh4iHm6VEoU7IiNyOoo3jzpOyOu634_bPrUQ
event_an_enroll: false
event_an_enroll_email_notify: true
event_an_enroll_default_value: false
event_an_enroll_allow_edit: true
event_an_enroll_email_subject: 'You are enrolled in the event [node:title]'
event_an_enroll_email_body: 'You have been enrolled in the event [node:title]. You can cancel your enrollment anytime using the following link: [social_event_an_enroll:enrolled_event].'
