_core:
  default_config_hash: jomlQHaaPEcwYHPqeYVyYG5vygu7z2CzzJlHdwiyJlU
enable_content_tagging: true
allow_category_split: true
use_category_parent: false
tag_node_type_book: false
tag_node_type_event: false
tag_node_type_landing_page: false
tag_node_type_page: false
tag_node_type_topic: true
tag_type_group: 0
tag_type_profile: 0
tag_node_type_dashboard: 0
