status:
  all: true
name: ''
short_name: ''
icons: null
start_url: /
background_color: '#ffffff'
theme_color: '#ffffff'
display: standalone
orientation: portrait
prompt_timing: 3
_core:
  default_config_hash: JqWa8QbtEoe7XmjZKW3EhsaxgqdFAsxFUC18xUULtBo
