_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 7bfc6e9e-9ebf-4e59-91b1-9f9052d99798
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /stream
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
