text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a <a href="[message:field_message_related_object:entity:url:absolute]">post</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a <a href="[message:field_message_related_object:entity:url:absolute]">post</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a <a href="[message:field_message_related_object:entity:url:absolute]">post</a> in the platform</p>'
