text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created new content <a href="[message:field_message_related_object:entity:url:absolute]">[message:node-title]</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created new content <a href="[message:field_message_related_object:entity:url:absolute]">[message:node-title]</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created new content <a href="[message:field_message_related_object:entity:url:absolute]">[message:node-title]</a> in the platform</p>'
