text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a new profile in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a new profile in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created a new profile in the platform</p>'
