text:
  -
    value: |
      <p><a href="[message:author:url:absolute]">[message:author:display-name]</a> reported <a href="[social_content_report:content_url]">content</a> as inappropriate</p>
    format: basic_html
  -
    value: |
      <p><a href="[message:author:url:absolute]">[message:author:display-name]</a> reported <a href="[social_content_report:content_url]">content</a> as inappropriate</p>
    format: full_html
  -
    value: |
      <p><a href="[message:author:url:absolute]">[message:author:display-name]</a> reported <a href="[social_content_report:content_url]">content</a> as inappropriate</p>
    format: basic_html
