text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created group <a href="[message:gurl]">[message:gtitle]</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created group <a href="[message:gurl]">[message:gtitle]</a> in the platform</p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> created group <a href="[message:gurl]">[message:gtitle]</a> in the platform</p>'
